// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metadata.proto

package hlmirbft

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// BlockMetadata stores data used by the MirBFT OSNs when
// coordinating with each other, to be serialized into
// block meta dta field and used after failres and restarts.
type BlockMetadata struct {
	// Maintains a mapping between the cluster's OSNs
	// and their Mir-BFT IDs.
	ConsenterIds []uint64 `protobuf:"varint,1,rep,packed,name=consenter_ids,json=consenterIds,proto3" json:"consenter_ids,omitempty"`
	// Carries the Mir-BFT ID value that will be assigned
	// to the next OSN that will join this cluster.
	NextConsenterId uint64 `protobuf:"varint,2,opt,name=next_consenter_id,json=nextConsenterId,proto3" json:"next_consenter_id,omitempty"`
	// Index of MirBft entry for current block.
	MirbftIndex uint64 `protobuf:"varint,3,opt,name=mirbft_index,json=mirbftIndex,proto3" json:"mirbft_index,omitempty"`
	// Last Mir-BFT checkpoint sequence number reached by consensus
	LastCheckpointSeqNo uint64 `protobuf:"varint,4,opt,name=last_checkpoint_seq_no,json=lastCheckpointSeqNo,proto3" json:"last_checkpoint_seq_no,omitempty"`
	// Contains the current agreed Mir-BFT network state
	NetworkState         []byte   `protobuf:"bytes,5,opt,name=network_state,json=networkState,proto3" json:"network_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockMetadata) Reset()         { *m = BlockMetadata{} }
func (m *BlockMetadata) String() string { return proto.CompactTextString(m) }
func (*BlockMetadata) ProtoMessage()    {}
func (*BlockMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{0}
}

func (m *BlockMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockMetadata.Unmarshal(m, b)
}
func (m *BlockMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockMetadata.Marshal(b, m, deterministic)
}
func (m *BlockMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockMetadata.Merge(m, src)
}
func (m *BlockMetadata) XXX_Size() int {
	return xxx_messageInfo_BlockMetadata.Size(m)
}
func (m *BlockMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_BlockMetadata proto.InternalMessageInfo

func (m *BlockMetadata) GetConsenterIds() []uint64 {
	if m != nil {
		return m.ConsenterIds
	}
	return nil
}

func (m *BlockMetadata) GetNextConsenterId() uint64 {
	if m != nil {
		return m.NextConsenterId
	}
	return 0
}

func (m *BlockMetadata) GetMirbftIndex() uint64 {
	if m != nil {
		return m.MirbftIndex
	}
	return 0
}

func (m *BlockMetadata) GetLastCheckpointSeqNo() uint64 {
	if m != nil {
		return m.LastCheckpointSeqNo
	}
	return 0
}

func (m *BlockMetadata) GetNetworkState() []byte {
	if m != nil {
		return m.NetworkState
	}
	return nil
}

// ClusterMetadata encapsulates metadata that is exchanged among cluster nodes
type ClusterMetadata struct {
	// Indicates active nodes in cluster that are reacheable by Raft leader
	ActiveNodes          []uint64 `protobuf:"varint,1,rep,packed,name=active_nodes,json=activeNodes,proto3" json:"active_nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterMetadata) Reset()         { *m = ClusterMetadata{} }
func (m *ClusterMetadata) String() string { return proto.CompactTextString(m) }
func (*ClusterMetadata) ProtoMessage()    {}
func (*ClusterMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_56d9f74966f40d04, []int{1}
}

func (m *ClusterMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterMetadata.Unmarshal(m, b)
}
func (m *ClusterMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterMetadata.Marshal(b, m, deterministic)
}
func (m *ClusterMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterMetadata.Merge(m, src)
}
func (m *ClusterMetadata) XXX_Size() int {
	return xxx_messageInfo_ClusterMetadata.Size(m)
}
func (m *ClusterMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterMetadata proto.InternalMessageInfo

func (m *ClusterMetadata) GetActiveNodes() []uint64 {
	if m != nil {
		return m.ActiveNodes
	}
	return nil
}

func init() {
	proto.RegisterType((*BlockMetadata)(nil), "hlmirbft.BlockMetadata")
	proto.RegisterType((*ClusterMetadata)(nil), "hlmirbft.ClusterMetadata")
}

func init() { proto.RegisterFile("metadata.proto", fileDescriptor_56d9f74966f40d04) }

var fileDescriptor_56d9f74966f40d04 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4e, 0x32, 0x31,
	0x14, 0x85, 0x33, 0x3f, 0xfc, 0xc6, 0x94, 0x41, 0xe2, 0x98, 0x98, 0x59, 0x02, 0x6e, 0x88, 0x86,
	0x99, 0x44, 0xf4, 0x05, 0x60, 0xc5, 0x42, 0x16, 0xb0, 0x73, 0xd3, 0x74, 0xda, 0x0b, 0x34, 0x94,
	0x5e, 0x68, 0x2f, 0x8a, 0x0f, 0xeb, 0xbb, 0x98, 0x52, 0x06, 0xdd, 0x7e, 0xe7, 0x7c, 0x69, 0xef,
	0x61, 0x37, 0x5b, 0x20, 0xa1, 0x04, 0x89, 0x62, 0xe7, 0x90, 0x30, 0xbb, 0x5e, 0x9b, 0xad, 0x76,
	0xd5, 0x92, 0xfa, 0xdf, 0x09, 0x6b, 0x8f, 0x0d, 0xca, 0xcd, 0xdb, 0xb9, 0x91, 0x3d, 0xb0, 0xb6,
	0x44, 0xeb, 0xc1, 0x12, 0x38, 0xae, 0x95, 0xcf, 0x93, 0x6e, 0x63, 0xd0, 0x9c, 0xa7, 0x17, 0x38,
	0x55, 0x3e, 0x7b, 0x64, 0xb7, 0x16, 0x8e, 0xc4, 0xff, 0x36, 0xf3, 0x7f, 0xdd, 0x64, 0xd0, 0x9c,
	0x77, 0x42, 0x30, 0xf9, 0x2d, 0x67, 0x3d, 0x96, 0xc6, 0xc7, 0xb8, 0xb6, 0x0a, 0x8e, 0x79, 0xe3,
	0x54, 0x6b, 0x45, 0x36, 0x0d, 0x28, 0x1b, 0xb1, 0x7b, 0x23, 0x3c, 0x71, 0xb9, 0x06, 0xb9, 0xd9,
	0xa1, 0xb6, 0xc4, 0x3d, 0xec, 0xb9, 0xc5, 0xbc, 0x79, 0x2a, 0xdf, 0x85, 0x74, 0x72, 0x09, 0x17,
	0xb0, 0x9f, 0x61, 0xf8, 0xa8, 0x05, 0xfa, 0x44, 0xb7, 0xe1, 0x9e, 0x04, 0x41, 0xfe, 0xbf, 0x9b,
	0x0c, 0xd2, 0x79, 0x7a, 0x86, 0x8b, 0xc0, 0xfa, 0x2f, 0xac, 0x33, 0x31, 0x07, 0x4f, 0xe0, 0x2e,
	0x07, 0xf6, 0x58, 0x2a, 0x24, 0xe9, 0x0f, 0xe0, 0x16, 0x15, 0xd4, 0xf7, 0xb5, 0x22, 0x9b, 0x05,
	0x34, 0x56, 0xec, 0x09, 0xdd, 0xaa, 0x58, 0x9a, 0xaf, 0xe7, 0x9d, 0x11, 0xb6, 0x58, 0x8a, 0xca,
	0x69, 0x19, 0xc7, 0xf3, 0x05, 0x3a, 0x05, 0x0e, 0x5c, 0x51, 0x8f, 0xf8, 0xfe, 0xba, 0xd2, 0xb4,
	0x3e, 0x54, 0x85, 0xc4, 0x6d, 0x59, 0x3b, 0x65, 0x74, 0x86, 0xd1, 0x19, 0xae, 0xb0, 0x3c, 0x6b,
	0x65, 0xad, 0x55, 0x57, 0xa7, 0x6c, 0xf4, 0x13, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x1a, 0x0f, 0xee,
	0x9e, 0x01, 0x00, 0x00,
}
