// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mirbft/configuration.proto

package mirbft

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ConfigMetadata is serialized and set as the value of ConsensusType.Metadata in
// a channel configuration when the ConsensusType.Type is set "mirbft".
type ConfigMetadata struct {
	Consenters           []*Consenter `protobuf:"bytes,1,rep,name=consenters,proto3" json:"consenters,omitempty"`
	Options              *Options     `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ConfigMetadata) Reset()         { *m = ConfigMetadata{} }
func (m *ConfigMetadata) String() string { return proto.CompactTextString(m) }
func (*ConfigMetadata) ProtoMessage()    {}
func (*ConfigMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a652948a8c6cd03, []int{0}
}

func (m *ConfigMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigMetadata.Unmarshal(m, b)
}
func (m *ConfigMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigMetadata.Marshal(b, m, deterministic)
}
func (m *ConfigMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigMetadata.Merge(m, src)
}
func (m *ConfigMetadata) XXX_Size() int {
	return xxx_messageInfo_ConfigMetadata.Size(m)
}
func (m *ConfigMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigMetadata proto.InternalMessageInfo

func (m *ConfigMetadata) GetConsenters() []*Consenter {
	if m != nil {
		return m.Consenters
	}
	return nil
}

func (m *ConfigMetadata) GetOptions() *Options {
	if m != nil {
		return m.Options
	}
	return nil
}

// Consenter represents a consenting node (i.e. replica).
type Consenter struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	ClientTlsCert        []byte   `protobuf:"bytes,3,opt,name=client_tls_cert,json=clientTlsCert,proto3" json:"client_tls_cert,omitempty"`
	ServerTlsCert        []byte   `protobuf:"bytes,4,opt,name=server_tls_cert,json=serverTlsCert,proto3" json:"server_tls_cert,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Consenter) Reset()         { *m = Consenter{} }
func (m *Consenter) String() string { return proto.CompactTextString(m) }
func (*Consenter) ProtoMessage()    {}
func (*Consenter) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a652948a8c6cd03, []int{1}
}

func (m *Consenter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consenter.Unmarshal(m, b)
}
func (m *Consenter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consenter.Marshal(b, m, deterministic)
}
func (m *Consenter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consenter.Merge(m, src)
}
func (m *Consenter) XXX_Size() int {
	return xxx_messageInfo_Consenter.Size(m)
}
func (m *Consenter) XXX_DiscardUnknown() {
	xxx_messageInfo_Consenter.DiscardUnknown(m)
}

var xxx_messageInfo_Consenter proto.InternalMessageInfo

func (m *Consenter) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Consenter) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Consenter) GetClientTlsCert() []byte {
	if m != nil {
		return m.ClientTlsCert
	}
	return nil
}

func (m *Consenter) GetServerTlsCert() []byte {
	if m != nil {
		return m.ServerTlsCert
	}
	return nil
}

// Options to be specified for all the hyperledger-labs/mirbft nodes. These can be modified on a
// per-channel basis.
type Options struct {
	// HeartbeatTicks is the number of ticks before a heartbeat is emitted
	// by a leader.
	HeartbeatTicks uint32 `protobuf:"varint,1,opt,name=HeartbeatTicks,proto3" json:"HeartbeatTicks,omitempty"`
	// SuspectTicks is the number of ticks a bucket may not progress before
	// the node suspects the epoch has gone bad.
	SuspectTicks uint32 `protobuf:"varint,2,opt,name=SuspectTicks,proto3" json:"SuspectTicks,omitempty"`
	// NewEpochTimeoutTicks is the number of ticks a replica will wait until
	// it suspects the epoch leader has failed.  This value must be greater
	// than 1, as rebroadcast ticks are computed as half this value.
	NewEpochTimeoutTicks uint32 `protobuf:"varint,3,opt,name=NewEpochTimeoutTicks,proto3" json:"NewEpochTimeoutTicks,omitempty"`
	// BufferSize is the total size of messages which can be held by the state
	// machine, pending application, for each node.  This is necessary because
	// there may be dependencies between messages (for instance, until a checkpoint
	// result is computed, watermarks cannot advance).  This should be set
	// to a minimum of a few MB.
	BufferSize           uint32   `protobuf:"varint,4,opt,name=BufferSize,proto3" json:"BufferSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Options) Reset()         { *m = Options{} }
func (m *Options) String() string { return proto.CompactTextString(m) }
func (*Options) ProtoMessage()    {}
func (*Options) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a652948a8c6cd03, []int{2}
}

func (m *Options) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Options.Unmarshal(m, b)
}
func (m *Options) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Options.Marshal(b, m, deterministic)
}
func (m *Options) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Options.Merge(m, src)
}
func (m *Options) XXX_Size() int {
	return xxx_messageInfo_Options.Size(m)
}
func (m *Options) XXX_DiscardUnknown() {
	xxx_messageInfo_Options.DiscardUnknown(m)
}

var xxx_messageInfo_Options proto.InternalMessageInfo

func (m *Options) GetHeartbeatTicks() uint32 {
	if m != nil {
		return m.HeartbeatTicks
	}
	return 0
}

func (m *Options) GetSuspectTicks() uint32 {
	if m != nil {
		return m.SuspectTicks
	}
	return 0
}

func (m *Options) GetNewEpochTimeoutTicks() uint32 {
	if m != nil {
		return m.NewEpochTimeoutTicks
	}
	return 0
}

func (m *Options) GetBufferSize() uint32 {
	if m != nil {
		return m.BufferSize
	}
	return 0
}

func init() {
	proto.RegisterType((*ConfigMetadata)(nil), "mirbft.ConfigMetadata")
	proto.RegisterType((*Consenter)(nil), "mirbft.Consenter")
	proto.RegisterType((*Options)(nil), "mirbft.Options")
}

func init() { proto.RegisterFile("mirbft/configuration.proto", fileDescriptor_4a652948a8c6cd03) }

var fileDescriptor_4a652948a8c6cd03 = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4a, 0xf3, 0x40,
	0x14, 0x85, 0xc9, 0xdf, 0xd2, 0xd2, 0x69, 0xd3, 0xf2, 0x0f, 0x2e, 0x82, 0x0b, 0x09, 0x59, 0x94,
	0xb8, 0x68, 0x82, 0x75, 0xe1, 0xbe, 0x45, 0x70, 0xa3, 0x42, 0xda, 0x95, 0x9b, 0x32, 0x99, 0xde,
	0x24, 0x43, 0x9b, 0x4c, 0xb8, 0x33, 0x51, 0x74, 0xeb, 0xd3, 0xf8, 0x96, 0xd2, 0x99, 0x54, 0xab,
	0xb8, 0x1b, 0xbe, 0xf3, 0x9d, 0xcb, 0x21, 0x21, 0xe7, 0xa5, 0xc0, 0x34, 0xd3, 0x31, 0x97, 0x55,
	0x26, 0xf2, 0x06, 0x99, 0x16, 0xb2, 0x8a, 0x6a, 0x94, 0x5a, 0xd2, 0x9e, 0xcd, 0x82, 0x8a, 0x8c,
	0x97, 0x26, 0xbe, 0x07, 0xcd, 0xb6, 0x4c, 0x33, 0x7a, 0x45, 0x08, 0x97, 0x95, 0x82, 0x4a, 0x03,
	0x2a, 0xcf, 0xf1, 0x3b, 0xe1, 0x70, 0xfe, 0x3f, 0xb2, 0x7a, 0xb4, 0x3c, 0x26, 0xc9, 0x89, 0x44,
	0x2f, 0x49, 0x5f, 0xd6, 0x87, 0xe3, 0xca, 0xfb, 0xe7, 0x3b, 0xe1, 0x70, 0x3e, 0x39, 0xfa, 0x8f,
	0x16, 0x27, 0xc7, 0x3c, 0x78, 0x77, 0xc8, 0xe0, 0xeb, 0x08, 0xa5, 0xa4, 0x5b, 0x48, 0xa5, 0x3d,
	0xc7, 0x77, 0xc2, 0x41, 0x62, 0xde, 0x07, 0x56, 0x4b, 0xd4, 0xe6, 0x92, 0x9b, 0x98, 0x37, 0x9d,
	0x92, 0x09, 0xdf, 0x0b, 0xa8, 0xf4, 0x46, 0xef, 0xd5, 0x86, 0x03, 0x6a, 0xaf, 0xe3, 0x3b, 0xe1,
	0x28, 0x71, 0x2d, 0x5e, 0xef, 0xd5, 0x12, 0xac, 0xa7, 0x00, 0x9f, 0x01, 0xbf, 0xbd, 0xae, 0xf5,
	0x2c, 0x6e, 0xbd, 0xe0, 0xc3, 0x21, 0xfd, 0x76, 0x1a, 0x9d, 0x92, 0xf1, 0x1d, 0x30, 0xd4, 0x29,
	0x30, 0xbd, 0x16, 0x7c, 0xa7, 0xcc, 0x1a, 0x37, 0xf9, 0x45, 0x69, 0x40, 0x46, 0xab, 0x46, 0xd5,
	0xc0, 0x5b, 0xcb, 0xee, 0xfb, 0xc1, 0xe8, 0x9c, 0x9c, 0x3d, 0xc0, 0xcb, 0x6d, 0x2d, 0x79, 0xb1,
	0x16, 0x25, 0xc8, 0xa6, 0x75, 0x3b, 0xc6, 0xfd, 0x33, 0xa3, 0x17, 0x84, 0x2c, 0x9a, 0x2c, 0x03,
	0x5c, 0x89, 0x37, 0x30, 0x73, 0xdd, 0xe4, 0x84, 0x2c, 0x0a, 0x32, 0x93, 0x98, 0x47, 0x05, 0x43,
	0x7c, 0x2d, 0x77, 0x95, 0xc8, 0x0b, 0x1d, 0x65, 0x2c, 0x45, 0xc1, 0xed, 0xaf, 0x54, 0x91, 0xc4,
	0x2d, 0x20, 0x60, 0xfb, 0xcd, 0x9f, 0x6e, 0x72, 0xa1, 0x8b, 0x26, 0x8d, 0xb8, 0x2c, 0xe3, 0xd3,
	0x56, 0x6c, 0x5b, 0x33, 0xdb, 0x9a, 0xe5, 0x32, 0x6e, 0x8b, 0xb1, 0x2d, 0xa6, 0x3d, 0x93, 0x5c,
	0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0x3a, 0xe5, 0xcb, 0xa5, 0x38, 0x02, 0x00, 0x00,
}
