// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mirbft/metadata.proto

package mirbftopts

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// BlockMetadata stores data used by the Raft OSNs when
// coordinating with each other, to be serialized into
// block meta dta field and used after failres and restarts.
type BlockMetadata struct {
	// Maintains a mapping between the cluster's OSNs
	// and their Raft IDs.
	ConsenterIds []uint64 `protobuf:"varint,1,rep,packed,name=consenter_ids,json=consenterIds,proto3" json:"consenter_ids,omitempty"`
	// Carries the Raft ID value that will be assigned
	// to the next OSN that will join this cluster.
	NextConsenterId uint64 `protobuf:"varint,2,opt,name=next_consenter_id,json=nextConsenterId,proto3" json:"next_consenter_id,omitempty"`
	// Index of etcd/raft entry for current block.
	RaftIndex            uint64   `protobuf:"varint,3,opt,name=raft_index,json=raftIndex,proto3" json:"raft_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockMetadata) Reset()         { *m = BlockMetadata{} }
func (m *BlockMetadata) String() string { return proto.CompactTextString(m) }
func (*BlockMetadata) ProtoMessage()    {}
func (*BlockMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ca8a3c69396d04a, []int{0}
}

func (m *BlockMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockMetadata.Unmarshal(m, b)
}
func (m *BlockMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockMetadata.Marshal(b, m, deterministic)
}
func (m *BlockMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockMetadata.Merge(m, src)
}
func (m *BlockMetadata) XXX_Size() int {
	return xxx_messageInfo_BlockMetadata.Size(m)
}
func (m *BlockMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_BlockMetadata proto.InternalMessageInfo

func (m *BlockMetadata) GetConsenterIds() []uint64 {
	if m != nil {
		return m.ConsenterIds
	}
	return nil
}

func (m *BlockMetadata) GetNextConsenterId() uint64 {
	if m != nil {
		return m.NextConsenterId
	}
	return 0
}

func (m *BlockMetadata) GetRaftIndex() uint64 {
	if m != nil {
		return m.RaftIndex
	}
	return 0
}

// ClusterMetadata encapsulates metadata that is exchanged among cluster nodes
type ClusterMetadata struct {
	// Indicates active nodes in cluster that are reacheable by Raft leader
	ActiveNodes          []uint64 `protobuf:"varint,1,rep,packed,name=active_nodes,json=activeNodes,proto3" json:"active_nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterMetadata) Reset()         { *m = ClusterMetadata{} }
func (m *ClusterMetadata) String() string { return proto.CompactTextString(m) }
func (*ClusterMetadata) ProtoMessage()    {}
func (*ClusterMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ca8a3c69396d04a, []int{1}
}

func (m *ClusterMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterMetadata.Unmarshal(m, b)
}
func (m *ClusterMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterMetadata.Marshal(b, m, deterministic)
}
func (m *ClusterMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterMetadata.Merge(m, src)
}
func (m *ClusterMetadata) XXX_Size() int {
	return xxx_messageInfo_ClusterMetadata.Size(m)
}
func (m *ClusterMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterMetadata proto.InternalMessageInfo

func (m *ClusterMetadata) GetActiveNodes() []uint64 {
	if m != nil {
		return m.ActiveNodes
	}
	return nil
}

func init() {
	proto.RegisterType((*BlockMetadata)(nil), "mirbft.BlockMetadata")
	proto.RegisterType((*ClusterMetadata)(nil), "mirbft.ClusterMetadata")
}

func init() { proto.RegisterFile("mirbft/metadata.proto", fileDescriptor_8ca8a3c69396d04a) }

var fileDescriptor_8ca8a3c69396d04a = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x31, 0x6b, 0x02, 0x41,
	0x10, 0x85, 0x31, 0x8a, 0x90, 0x89, 0x22, 0x39, 0x08, 0xd8, 0x04, 0x8c, 0x69, 0x24, 0x70, 0xbb,
	0x45, 0x02, 0xe9, 0xb5, 0xb2, 0x48, 0x0a, 0xcb, 0x34, 0xc7, 0xde, 0xee, 0xdc, 0xdd, 0xa2, 0xb7,
	0x13, 0x66, 0xc7, 0x60, 0xaa, 0xfc, 0xf5, 0x70, 0xae, 0x31, 0xb6, 0xdf, 0x7b, 0x1f, 0xbc, 0x07,
	0x77, 0xad, 0xe7, 0xb2, 0x12, 0xdd, 0xa2, 0x18, 0x67, 0xc4, 0xa8, 0x4f, 0x26, 0xa1, 0x6c, 0x98,
	0xf0, 0xfc, 0x07, 0xc6, 0xcb, 0x1d, 0xd9, 0xed, 0xdb, 0x29, 0xce, 0x1e, 0x61, 0x6c, 0x29, 0x44,
	0x0c, 0x82, 0x5c, 0x78, 0x17, 0xa7, 0xbd, 0x59, 0x7f, 0x31, 0xd8, 0x8c, 0xce, 0x70, 0xed, 0x62,
	0xf6, 0x04, 0xb7, 0x01, 0x0f, 0x52, 0x5c, 0x36, 0xa7, 0x57, 0xb3, 0xde, 0x62, 0xb0, 0x99, 0x74,
	0xc1, 0xea, 0xbf, 0x9c, 0xdd, 0x03, 0xb0, 0xa9, 0xa4, 0xf0, 0xc1, 0xe1, 0x61, 0xda, 0x3f, 0x96,
	0xae, 0x3b, 0xb2, 0xee, 0xc0, 0xfc, 0x05, 0x26, 0xab, 0xdd, 0x3e, 0x0a, 0xf2, 0x79, 0xc2, 0x03,
	0x8c, 0x8c, 0x15, 0xff, 0x85, 0x45, 0x20, 0x87, 0x7f, 0x0b, 0x6e, 0x12, 0x7b, 0xef, 0xd0, 0xb2,
	0x81, 0x9c, 0xb8, 0x56, 0x8d, 0x61, 0xfe, 0x6e, 0xb7, 0xc1, 0xd7, 0x8d, 0xa8, 0xca, 0x94, 0xec,
	0x6d, 0xfa, 0x17, 0x15, 0xb1, 0x43, 0x46, 0x56, 0xe9, 0xe7, 0xc7, 0x6b, 0xed, 0xa5, 0xd9, 0x97,
	0xca, 0x52, 0xab, 0x2f, 0x2d, 0x9d, 0xac, 0x3c, 0x59, 0x79, 0x4d, 0xfa, 0x24, 0xea, 0x24, 0x96,
	0xc3, 0x63, 0xf2, 0xfc, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x20, 0xe0, 0xdd, 0x48, 0x01, 0x00,
	0x00,
}
